# -*- coding: utf-8 -*-
"""Projek 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAOEZ4HK0ggY9YB7MI9kNhXRurMZEtJn
"""

import pandas as pd
import os
from datetime import datetime

# Install xlsxwriter if not already installed
!pip install xlsxwriter

# 1. LOAD DATA
df = pd.read_csv('itemsppni.csv', sep=';')

# Bersihkan harga dan hitung demand per baris
df['price_numeric'] = df['price by item'].str.replace('Rp ', '', regex=False).str.replace('.', '', regex=False).astype(int)
df['demand'] = df['total_units'] - df['remaining']

# 2. PROSES PENGELOMPOKAN (Grouping) - Solusi untuk barang ganda
# Kita jumlahkan semua berdasarkan Fakultas dan Nama Barang
df_grouped = df.groupby(['faculty', 'name_items']).agg({
    'total_units': 'sum',
    'remaining': 'sum',
    'demand': 'sum',
    'price_numeric': 'first' # Ambil harga salah satu saja karena sama
}).reset_index()

# Hitung nilai aset berdasarkan hasil pengelompokan
df_grouped['asset_value_remaining'] = df_grouped['remaining'] * df_grouped['price_numeric']

# 3. ANALISIS DATA UNTUK SHEET
# Rekomendasi Reorder (Priority 0)
priority_order = df_grouped[df_grouped['remaining'] == 0]

# Analisis Permintaan (Top 10 vs Low 10 dari data yang sudah dikelompokkan)
top_demand = df_grouped.sort_values(by='demand', ascending=False).head(10)
low_demand = df_grouped[df_grouped['demand'] > 0].sort_values(by='demand', ascending=True).head(10)

# 4. PENYIMPANAN EXCEL
tanggal_sekarang = datetime.now().strftime("%Y-%m-%d")
nama_folder = f"Laporan_{tanggal_sekarang}"
if not os.path.exists(nama_folder): os.makedirs(nama_folder)

nama_file = f"{nama_folder}/Laporan_Final_Terintegrasi_{tanggal_sekarang}.xlsx"

with pd.ExcelWriter(nama_file, engine='xlsxwriter') as writer:
    # Sheet 1: Master Data (Tetap tampilkan data asli untuk audit)
    df.to_excel(writer, sheet_name='Master_Data_Original', index=False)

    # Sheet 2: Rekomendasi Reorder (Sesuai permintaan: Total dulu baru Prioritas 0)
    df_grouped.sort_values(by='remaining').to_excel(writer, sheet_name='Rekomendasi_Reorder', index=False)

    # Tambahkan tabel Prioritas 0 di bawahnya
    worksheet_reorder = writer.sheets['Rekomendasi_Reorder']
    start_row = len(df_grouped) + 3
    worksheet_reorder.write(start_row - 1, 0, "--- DAFTAR PRIORITAS ORDER (STOK 0) ---")
    priority_order.to_excel(writer, sheet_name='Rekomendasi_Reorder', startrow=start_row, index=False)

    # Sheet 3: Analisis Permintaan (Top vs Low yang sudah akurat)
    top_demand.to_excel(writer, sheet_name='Analisis_Permintaan', index=False)
    worksheet_demand = writer.sheets['Analisis_Permintaan']
    low_start_row = len(top_demand) + 3
    worksheet_demand.write(low_start_row - 1, 0, "--- 10 PERMINTAAN TERENDAH (BARANG KURANG LAKU) ---")
    low_demand.to_excel(writer, sheet_name='Analisis_Permintaan', startrow=low_start_row, index=False)

print(f"✅ Selesai! Laporan sudah jauh lebih akurat sekarang: {nama_file}")